config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  get 'confirmation/index'
  root to: redirect('/homepage/index')
  devise_for :users
  resources :voos
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
     can :manage, :all
    else
     can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/voo.rb
class Voo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/confirmation_controller.rb
class ConfirmationController < ApplicationController
  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin)
    end
end

app/controllers/voos_controller.rb
class VoosController < ApplicationController
  before_action :set_voo, only: [:show, :edit, :update, :destroy]

  # GET /voos
  # GET /voos.json
  def index
    @voos = Voo.all
  end

  # GET /voos/1
  # GET /voos/1.json
  def show
  end

  # GET /voos/new
  def new
    @voo = Voo.new
  end

  # GET /voos/1/edit
  def edit
  end

  # POST /voos
  # POST /voos.json
  def create
    @voo = Voo.new(voo_params)

    respond_to do |format|
      if @voo.save
        format.html { redirect_to @voo, notice: 'Voo was successfully created.' }
        format.json { render :show, status: :created, location: @voo }
      else
        format.html { render :new }
        format.json { render json: @voo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voos/1
  # PATCH/PUT /voos/1.json
  def update
    respond_to do |format|
      if @voo.update(voo_params)
        format.html { redirect_to @voo, notice: 'Voo was successfully updated.' }
        format.json { render :show, status: :ok, location: @voo }
      else
        format.html { render :edit }
        format.json { render json: @voo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voos/1
  # DELETE /voos/1.json
  def destroy
    @voo.destroy
    respond_to do |format|
      format.html { redirect_to voos_url, notice: 'Voo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voo
      @voo = Voo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voo_params
      params.require(:voo).permit(:codigo, :destino, :data, :preco, :empresa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/voos_helper.rb
module VoosHelper
end

app/views/confirmation/index.html.erb
<div class= "container">
<h1>Comprovante de reserva</h1>
<h3>Voo reservado com sucesso!</h3>
<img src="https://cdn.pixabay.com/photo/2012/04/10/17/24/airplane-26560_960_720.png">
</div>

app/views/homepage/index.html.erb
<html>   
<style>
body {
background-color: lightgrey
}
</style>
<body> 
    <img src="https://i.imgur.com/0PyREuz.png" alt="Flying Airplane"> 

    <div class="container">
        <h1>Contextualização</h1>
        <h3>Este é um trabalho da disciplina de Orientação a Objetos desenvolvido utilizando a linguagem Ruby juntamente com a framework Rails.</h3>
        <h3>O site consiste em um sistema de reservas de voos, no qual um usuário normal consegue reservar voos disponíveis, e os usuários administradores podem adicionar novos voos e editar usuários.</h3>
        <br>
        <br>
        <br>
</body> 
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FGAirlines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
  body {
  background-color: lightgrey
  }
  </style>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/homepage/index">FGAirlines</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/voos">Voos</a></li>
          <li><a href="/users">Usuários</a></li>
        <% if user_signed_in? %> 
          <li><a>Logado como: <%= current_user.email %></a></li>
          <li><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li><%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> </li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  <style>
    .footer {
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: black;
      color: white;
      text-align: center;
    }
  </style>
  <div class="footer">
  <p>FGAirlines © 2019</p>
  <p>Developed by Mateus Gomes and Vinicius Saturnino</p>
</div>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editando Usuário</h1>

<%= render 'form', user: @user %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<style>
body {
background-color: lightblue
}
</style>
<div class="container">
  <h1>Usuários Cadastrados</h1>
  <table>
  <div class="row">
    <div class="col-sm-1" style="background-color:lightgrey;"><h3>Admin</h3></div>
    <div class="col-sm-3" style="background-color:grey;"><h3>Username</h3></div>
  </div>

  <div class="row">
    <div class="col-sm-4" style="background-color:black;"></div>
  </div>
  <div class="row">
    <div class="col-sm-4" style="background-color:black;"></div>
  </div>

  <% @users.each do |user| %>
    <div class="row">
      <div class="col-sm-1" style="background-color:lightyellow;"><h5><%= user.admin %></h5></div>
      <div class="col-sm-3" style="background-color:lavender;"><h5><%= user.name %></h5></div>
      <button type="button" class="btn btn-info"><%= link_to 'Mostrar', user %></button>
      <% if can? :create, User %>
        <button type="button" class="btn btn-warning"><%= link_to 'Editar', edit_user_path(user) %></button>
      <% end %>
      <% if can? :create, User %>
       <button type="button" class="btn btn-danger"><%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Tem certeza?' } %></button>
      <% end %>
    </div>
    <div class="row">
      <div class="col-sm-4" style="background-color:black;"></div>
    </div>
    <div class="row">
      <div class="col-sm-4" style="background-color:black;"></div>
    </div>  
  <% end %>

</div>

</table>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class ="container">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<% if can? :create, User %>
    <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>

<%= link_to 'Back', users_path %>
</div>

app/views/voos/_form.html.erb
<%= form_with(model: voo, local: true) do |form| %>
  <% if voo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voo.errors.count, "error") %> prohibited this voo from being saved:</h2>

      <ul>
        <% voo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :destino %>
    <%= form.text_field :destino %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/voos/edit.html.erb
<h1>Editing Voo</h1>

<%= render 'form', voo: @voo %>

<%= link_to 'Show', @voo %> |
<%= link_to 'Back', voos_path %>

app/views/voos/index.html.erb
<p id="notice"><%= notice %></p>
<style>
body {
background-color: lightblue
}
</style>

<div class="container">

  <table>
      <div class="row">
        <div class="col-sm-1" style="background-color:lightgrey;"><h3>Código</h3></div>
        <div class="col-sm-2" style="background-color:grey;"><h3>Destino</h3></div>
        <div class="col-sm-2" style="background-color:lightgrey;"><h3>Data</h3></div>
        <div class="col-sm-2" style="background-color:grey;"><h3>Preço</h3></div>
        <div class="col-sm-2" style="background-color:lightgrey;"><h3>Empresa</h3></div>
      </div>

      <div class="row">
      <div class="col-sm-9" style="background-color:black;"></div>
    </div>
    <div class="row">
      <div class="col-sm-9" style="background-color:black;"></div>
    </div>
      <% @voos.each do |voo| %>
        <div class="row">
          <div class="col-sm-1" style="background-color:lightyellow;"><h5><%= voo.codigo %></h5></div>
          <div class="col-sm-2" style="background-color:lightgreen;"><h5><%= voo.destino %></h5></div>
          <div class="col-sm-2" style="background-color:lightyellow;"><h5><%= voo.data %></h5></div>
          <div class="col-sm-2" style="background-color:lightgreen;"><h5>R$ <%= voo.preco %></h5></div>
          <div class="col-sm-2" style="background-color:lightyellow;"><h5><%= voo.empresa %></h5></div>
          <button type="button" class="btn btn-info"><%= link_to 'Reservar', "/confirmation/index" %></button>
          <% if can? :create, User %>
            <button type="button" class="btn btn-warning"><%= link_to 'Editar', edit_voo_path(voo) %></button>
          <% end %>
          <% if can? :create, User %>
          <button type="button" class="btn btn-danger"><%= link_to 'Apagar', voo, method: :delete, data: { confirm: 'Tem certeza?' } %></button>
          <% end %>
        </div>
        <div class="row">
          <div class="col-sm-9" style="background-color:black;"></div>
        </div>
        <div class="row">
          <div class="col-sm-9" style="background-color:black;"></div>
        </div>  

      <% end %>
  </table>

  <br>

  <% if can? :create, Voo %>
    <button type="button" class="btn"><%= link_to 'Adicionar Voo', new_voo_path %></button>
  <% end %>

app/views/voos/new.html.erb
<div class="container">
<h1>Novo Voo</h1>

<%= render 'form', voo: @voo %>

<%= link_to 'Back', voos_path %>
</div>

app/views/voos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <strong>Codigo:</strong>
  <%= @voo.codigo %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @voo.destino %>
</p>

<p>
  <strong>Data:</strong>
  <%= @voo.data %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @voo.preco %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @voo.empresa %>
</p>

<ul class="navbar-nav mr-auto">
  <li class="nav-item active">
    <a class="nav-link" href="/confirmation/index">Reservar</a>
  </li>
  ...
</ul>

<% if can? :create, Voo %>
    <%= link_to 'Edit', edit_voo_path(@voo) %>
<% end %>
<%= link_to 'Back', voos_path %>
</div>